package rpgcombatmanager.model.enums;

public enum ConditionTypes {
	BLINDED, CHARMED, DEAFENED, FRIGHTENED, GRAPPLED, INCAPACITATED, INVISIBLE, PARALYZED, PETRIFIED, POISONED, PRONE,
	RESTRAINED, STUNNED, UNCONSCIOUS, EXHAUSTION;
}
