package rpgcombatmanager.model.enums;

public enum LanguageTypes {
	COMMON, DWARVISH, ELVISH, GIANT, GNOMISH, GOBLIN, HALFLING, ORC, ABYSSAL, CELESTIAL, DEEP_SPREECH, DRACONIC,
	INFERNAL, PRIMORDIAL, SYLVAN, UNDERCOMMON;
}
